// <auto-generated />
using System;
using Ironfront.Matchmaking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ironfront.Matchmaking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MatchmakingDbContext))]
    [Migration("20260707213559_AddBattleQueueTeamsAndRules")]
    partial class AddBattleQueueTeamsAndRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleJoinTicket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("BattleServerInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("TicketId");

                    b.HasIndex("MatchId", "MatchPlayerId");

                    b.HasIndex("BattleServerInstanceId", "Status", "ExpiresAtUtc");

                    b.ToTable("battle_join_tickets", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleMatch", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("BattleServerInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedPlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ModeRevision")
                        .HasColumnType("integer");

                    b.Property<string>("RulesSnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WaitingForPlayersAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MatchId");

                    b.HasIndex("ModeId", "ModeRevision");

                    b.HasIndex("BattleServerInstanceId", "Status", "CreatedAtUtc");

                    b.ToTable("battle_matches", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleMatchPlayer", b =>
                {
                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialVehicleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerSlotIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TeamSlotIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchPlayerId");

                    b.HasIndex("MatchId", "PlayerSlotIndex")
                        .IsUnique();

                    b.HasIndex("MatchId", "UserId")
                        .IsUnique();

                    b.HasIndex("MatchId", "Status", "CreatedAtUtc");

                    b.HasIndex("MatchId", "TeamId", "TeamSlotIndex")
                        .IsUnique();

                    b.ToTable("battle_match_players", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleQueueEntry", b =>
                {
                    b.Property<Guid>("QueueEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("InitialVehicleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ModeRevision")
                        .HasColumnType("integer");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte>("VehicleBattleRatingTenths")
                        .HasColumnType("smallint");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("QueueEntryId");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Queued', 'Matched')");

                    b.HasIndex("ModeId", "ModeRevision", "Status", "VehicleBattleRatingTenths", "QueuedAtUtc");

                    b.ToTable("battle_queue_entries", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleServerCommand", b =>
                {
                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BattleServerInstanceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("CommandId");

                    b.HasIndex("MatchId");

                    b.HasIndex("BattleServerInstanceId", "State", "CreatedAtUtc");

                    b.ToTable("battle_server_commands", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleServerSlot", b =>
                {
                    b.Property<string>("ServerInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActiveMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServerInstanceId");

                    b.HasIndex("HostId");

                    b.HasIndex("Region", "Status", "LastHeartbeatUtc");

                    b.ToTable("battle_server_slots", (string)null);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleJoinTicket", b =>
                {
                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleServerSlot", null)
                        .WithMany()
                        .HasForeignKey("BattleServerInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleMatchPlayer", null)
                        .WithMany()
                        .HasForeignKey("MatchId", "MatchPlayerId")
                        .HasPrincipalKey("MatchId", "MatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleMatch", b =>
                {
                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleServerSlot", null)
                        .WithMany()
                        .HasForeignKey("BattleServerInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleMatchPlayer", b =>
                {
                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleQueueEntry", b =>
                {
                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ironfront.Matchmaking.Domain.Entities.BattleServerCommand", b =>
                {
                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleServerSlot", null)
                        .WithMany()
                        .HasForeignKey("BattleServerInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ironfront.Matchmaking.Domain.Entities.BattleMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
